# SPDX-FileCopyrightText: The Pion community <https://pion.ly>
# SPDX-License-Identifier: MIT

[server]
host-name=avahi-test
domain-name=local
use-ipv4=yes
use-ipv6=no
allow-interfaces=eth0
enable-dbus=yes

[wide-area]
enable-wide-area=no

[publish]
publish-addresses=yes
publish-hinfo=no
publish-workstation=no

[reflector]
enable-reflector=no

[rlimits]
